Task_1_1_1
m1Myp/OOP pull request #1
Opened 2022-09-18 12:01 UTC by m1Myp

2022-09-18 12:33 UTC, Leidenn2509 requested changes
По стилю там у вас `.yml` старый. В последней джобе должен быть путь до конфига.
https://github.com/Leidenn2509/OOP_workflow/blob/master/.github/workflows/oop.yml

2022-09-18 12:37 UTC, m1Myp commented
А, черт

2022-09-18 12:39 UTC, m1Myp commented
> По стилю там у вас `.yml` старый. В последней джобе должен быть путь до конфига. https://github.com/Leidenn2509/OOP_workflow/blob/master/.github/workflows/oop.yml

Меняю воркфлоу всё падает T_T

2022-09-18 12:46 UTC, m1Myp commented
Теперь лучше?

2022-09-19 07:39 UTC, m1Myp commented
Я не знаю, что я сейчас сделал, но я надеюсь я вам ничего не заспамил

2022-09-19 08:15 UTC, Leidenn2509 requested changes
Перейдите во вкладку `Files changed` и откройте свои `.java` файлы. Там будут ворнинги относительно оформления вашего кода. Их нужно исправить

2022-09-19 08:15 UTC, Leidenn2509 commented on Task_1_1_1/src/test/java/ru/nsu/fit/oop/lab1/HeapSortTests.java
> +        }
Желательно, чтобы один тест охватывал какой-то отдельный случай по смыслу. Вынесите в отдельные тесты случай с пустым массивом и слуай с одним элементом

2022-09-19 08:58 UTC, m1Myp commented on Task_1_1_1/src/test/java/ru/nsu/fit/oop/lab1/HeapSortTests.java
> +        }
В прошлом году Иван говорил, что это все простые тесты и их можно было бы запихнуть, ну ладно, исправим :)

2022-09-19 09:24 UTC, m1Myp commented
Он мне кидает такие варнинги
![image](https://user-images.githubusercontent.com/55120919/190987964-17593681-3314-4685-b886-16f30c7d30a8.png)
 Их тоже надо исправлять? Типо скобки для одной функции в форе/ифе

2022-09-20 11:24 UTC, Leidenn2509 approved these changes

2022-09-20 11:27 UTC, Leidenn2509 commented
Ваша ветка не может быть заребейжена из-за конфликта. Попробуйте локально перейти на ветку Task_1_1_1 и сделать `git rebase master`, это должно принести все изменения с мастера в вашу ветку и таким образом, если конфликты действительно есть, их можно будет разрешить через айдию. https://www.freecodecamp.org/news/the-ultimate-guide-to-git-merge-and-git-rebase/#:~:text=To%20rebase%2C%20make%20sure%20you,you%20want%20to%20rebase%20on). . Сами ПР не мержите/ребейзите, этим занимаюсь я

2022-09-20 11:35 UTC, m1Myp commented
> git rebase master

А если я не работаю через гит баш и поставлю его, я могу сломать все напрочь?

2022-09-21 02:38 UTC, m1Myp commented
Вроде заребейзил, он уже просит замёрджить в майн, но я этого делать не буду

2022-09-26 03:32 UTC, merged