Task_2_1_1
m1Myp/OOP pull request #11
Opened 2023-02-14 07:36 UTC by m1Myp

Тесты есть(примерные), а кода нет, опять

2023-02-15 03:26 UTC, m1Myp commented
Боже, я залил коммит вчера и забыл вас в ревьюеры добавить

2023-02-15 03:26 UTC, m1Myp commented
Можете поставить что софт дедлайн сдан?

2023-02-15 03:28 UTC, m1Myp commented
![image](https://user-images.githubusercontent.com/55120919/218919989-19967d4e-97d6-4cac-8327-839720c99e0f.png)

2023-02-17 09:18 UTC, alradish requested changes
Вижу дату коммитов, софт проставил по ним

2023-06-22 15:18 UTC, alradish approved these changes

2023-06-22 15:18 UTC, merged