Task_1_2_1
m1Myp/OOP pull request #3
Opened 2022-09-20 11:11 UTC by m1Myp

2022-09-21 10:52 UTC, Leidenn2509 requested changes

2022-09-21 10:52 UTC, Leidenn2509 commented on Task_1_2_1/1
> +
шо

2022-09-21 10:52 UTC, Leidenn2509 commented on Task_1_2_1/build.bat
> +jar cf .\batch\jar\HeapSort.jar -C .\batch\bin\ .
Это уже не нужно

2022-09-21 10:52 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
> +    private int id;
Это читается как айди, а вы, скорее всего, имели в виду индекс. Именна должны быть понятными, не экономьте на символах

2022-09-21 10:52 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
> +    private final Class<T> stackClass;
А зачем?

2022-09-21 10:52 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
> +
Лишняя пустая строчка

2022-09-21 10:52 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
> +    public void push(T elem) {
А если null?

2022-09-21 10:52 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
> +            return arr[--id];
Добавьте уменьшение размера буффера

2022-09-21 10:52 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
> +        Stack<T> returnStack = new Stack<>(count, stackClass);
Создание стека лучше перенести в иф, так как иногда вы будете создавать стек и потом не будете его использовать

2022-09-21 10:55 UTC, m1Myp commented on Task_1_2_1/1
> +
А, файлик не удалил

2022-09-21 10:55 UTC, m1Myp commented on Task_1_2_1/build.bat
> +jar cf .\batch\jar\HeapSort.jar -C .\batch\bin\ .
Well...

2022-09-21 11:28 UTC, m1Myp commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
> +    private final Class<T> stackClass;
Потому что мы используем 1 класс элементов в стэке, чтобы позже использовать в том же реаллоке, чтобы массив построить с нужным нам типом, который мы задали изначально

2022-09-23 09:46 UTC, Leidenn2509 requested changes

2022-09-23 09:46 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
> +            return temp;
Имелось ввиду добавить поддержку уменьшения массива, по аналогии с увеличением в `push`

2022-09-23 09:46 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
>          arr = (T[]) Array.newInstance(stackClass, maxSize);
Кажется, что констукция `(T[]) new Object[maxSize]` полностью эквивалентна конструкции `(T[]) Array.newInstance(stackClass, maxSize);`, только при этом не использует переменную `stackClass`.

2022-09-29 09:09 UTC, Leidenn2509 requested changes

2022-09-29 09:09 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/fit/oop/lab2/Stack.java
> +    public Stack<T> popStack(int count) throws EmptyStackException {
Здесь тоже нужно уменьшить массив

2022-10-06 18:25 UTC, Leidenn2509 approved these changes

2022-10-06 18:25 UTC, merged