Task_1_3_1
m1Myp/OOP pull request #5
Opened 2022-09-21 03:36 UTC by m1Myp

2022-11-07 07:28 UTC, m1Myp commented
Моё время пришло....
На локальной машине оно работает нормально (Задача которая у меня лежит с прошлого года), но оно не билдится тут, вопрос - почему?

2022-11-11 08:08 UTC, alradish requested changes
Нужно реализовать zFunction

2022-11-11 08:08 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/fit/oop/lab2/SubstringSearch.java
> +    public static ArrayList<Integer>
`List`. Используйте более общий тип `List`, чтобы сокрыть реализацию.

2022-11-11 08:08 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/fit/oop/lab2/SubstringSearch.java
> +    finiteStateMashine(Reader file, String str) throws IOException {
Лучше переименовать параметр, так как под ридером не обязательно находится файл

2022-11-11 08:08 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/fit/oop/lab2/SubstringSearch.java
> +        ArrayList<Integer> indexes = new ArrayList<>();
`List`

2022-11-28 11:29 UTC, m1Myp commented
Ревьюдог исправлю завтра, надеюсь код пройдет, я его переписал с 0ля

2022-12-12 03:17 UTC, alradish requested changes
В целом общее замечание это имена переменных и разбиение на функции. 
Буду честен я не смог разобраться в вашем коде. Пожалуйста назовите всё понятно + разбейте по функциям. Дедлайн для вас подвину до 14.12.2022

2022-12-12 03:17 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/fit/oop/lab2/SubstringSearch.java
> +        var m = needle.length();
Почему var, а не int? Тоже самое количество букв, но зато не нужно гадать.

2022-12-12 03:17 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/fit/oop/lab2/SubstringSearch.java
> +        var s = needle.toCharArray();
Ну тут то точно нужен тип

2022-12-12 03:17 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/fit/oop/lab2/SubstringSearch.java
> +        var rdr = new BufferedReader(reader);
Делаю запрос на поставку символов для использования их на именования переменных

2022-12-12 03:17 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/fit/oop/lab2/SubstringSearch.java
> +        int maxZ = 0;
Чем они отличаются. По имени непонятно

2022-12-12 03:17 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/fit/oop/lab2/SubstringSearch.java
> +        var ret = new ArrayList<Integer>();
var можно использовать только если у вас достаточно информации из контекста. Здесь у вас есть контекст типа (new справа), но обсолютно неинформативные имена

2022-12-14 12:40 UTC, m1Myp commented
Я сделал все красивенько. Просто тогда был дедлайн и я делал все на скорую руку.... Кто ж знал что дедлайн сдвинется

2022-12-17 13:28 UTC, alradish approved these changes

2022-12-17 13:29 UTC, merged