Task_1_2_2
m1Myp/OOP pull request #6
Opened 2022-10-09 09:40 UTC by m1Myp

2022-10-09 09:44 UTC, m1Myp commented
Там он ругается на чекстайл в джавадоках, потом перепишу
Надо ли реализовывать toArray для данной задачи?

2022-10-11 14:57 UTC, Leidenn2509 requested changes
- Тесты
- Должно быть два вида итератора
- Дожна быть возможность получить поддерево

2022-10-11 14:57 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/fit/oop/lab3/Tree.java
> +    private Node root;
1. Кажется, что это лишняя обертка.
2. Дерево не должно быть бинарным

2022-10-11 14:57 UTC, Leidenn2509 commented
> Там он ругается на чекстайл в джавадоках, потом перепишу Надо ли реализовывать toArray для данной задачи?

Не нужно

2022-10-12 15:19 UTC, m1Myp commented on Task_1_2_2/src/main/java/ru/nsu/fit/oop/lab3/Tree.java
> +    private Node root;
Про 2 пункт я категорически забыл :(

2022-10-18 09:09 UTC, Leidenn2509 requested changes
- Доделать итератор
- Добавьте конструктор

2022-10-18 09:09 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/fit/oop/lab3/Tree.java
> +        T[] treeArr = treeMap.get(root);
1. Кажется тут `null`, так как я не вижу как ещё root мог попасть в `treeMap`
2. Для чего вообще нужна эта структура?

2022-10-18 09:09 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/fit/oop/lab3/Tree.java
> +    public boolean add(T member) {
Здесь конечно хочется, чтобы при добавлении создавалось ещё одно дерево (с одним элементом) и добавлялось как ребёнок к текущей ноде (как я понял `private Tree<T>[] subtree;` это дети текущей ноды).

2022-10-18 09:09 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/fit/oop/lab3/Tree.java
> +        System.arraycopy(treeArr, 0, newTreeArr, 0, treeArr.length);
Если вам приходится так делать, то воспользуйтесь листом. Он буквально для этого и был сделан

2022-10-18 09:09 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/fit/oop/lab3/Tree.java
> +    private Map<T, T[]> treeMap;
Что-то в вашем коде всё очень запутанно и страшно. Я подозреваю, что весь раздор вносит это поле. Я, к сожаению, не понимаю зачем оно нужно. Попробуйте сделать без него

2022-10-18 09:09 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/fit/oop/lab3/Tree.java
> +    private Tree<T>[] subtree;
Колелкции лучше называть в множественном числе

2022-12-25 18:43 UTC, alradish approved these changes

2022-12-25 18:43 UTC, merged