Task_1_4_1
m1Myp/OOP pull request #8
Opened 2022-11-23 15:41 UTC by m1Myp

2022-11-24 04:13 UTC, m1Myp commented
Залил вчера, забыл на ревью кинуть. Гений? Гений

2022-12-06 12:21 UTC, alradish requested changes

2022-12-06 12:21 UTC, alradish commented on Task_1_4_1/src/main/java/ru/nsu/fit/oop/lab4/GradeBook.java
> +    public GradeBook(String name, Course[] crs) {
crs=>courses

2022-12-06 12:21 UTC, alradish commented on Task_1_4_1/src/main/java/ru/nsu/fit/oop/lab4/GradeBook.java
> +public class GradeBook {
Добавьте маркер текущего семестра + возможность выставить оценку

2022-12-18 08:44 UTC, m1Myp commented on Task_1_4_1/src/main/java/ru/nsu/fit/oop/lab4/GradeBook.java
> +public class GradeBook {
СетМарк реализовал в классе Маркс
Маркер текущего семестра добавил

2022-12-18 08:45 UTC, m1Myp commented on Task_1_4_1/src/main/java/ru/nsu/fit/oop/lab4/GradeBook.java
> +    public GradeBook(String name, Course[] crs) {
Надеюсь я правильно понял условие, а то оно слишком расплывчато

2022-12-18 20:24 UTC, m1Myp commented
Я опять забыл зареквестить ревью, не снимайте балл :(

2022-12-19 03:01 UTC, alradish approved these changes

2022-12-19 03:02 UTC, merged