Task_1_5_1
m1Myp/OOP pull request #9
Opened 2022-12-08 04:57 UTC by m1Myp

надеюсь софт дедлайн не сгорел....

2022-12-14 12:46 UTC, m1Myp commented
Тесты есть, а кода нет, для них нет магия...

2022-12-19 02:45 UTC, alradish requested changes
> Тесты есть, а кода нет, для них нет магия...  

Так-то класс

2022-12-23 14:33 UTC, m1Myp commented
Я сдаюсь, я не знаю, что здесь не так, на локальной машине все работает т.к. я в IDEA подключил фичу recordов, а на вашем тестере я так и не понял как это сделать (смотреть число коммитов и плакать)

2022-12-23 14:33 UTC, m1Myp commented
![image](https://user-images.githubusercontent.com/55120919/209352505-8e70de26-e939-4815-bb50-303132fc9823.png)

2022-12-25 10:22 UTC, alradish requested changes
ревью дог

2022-12-25 10:22 UTC, alradish commented on Task_1_5_1/src/main/java/ru/nsu/fit/oop/lab6/Calculator.java
> +}
Вынесите в отдельный файл

2022-12-25 10:22 UTC, alradish commented on Task_1_5_1/src/main/java/ru/nsu/fit/oop/lab6/Calculator.java
> +    Calculator() {
Модификатор

2022-12-25 10:22 UTC, alradish commented on Task_1_5_1/src/main/java/ru/nsu/fit/oop/lab6/Calculator.java
> +            throw new UnknownTokenException("Unknown token: " + s, s);
Нужна фабрика. Сущность которой вы передадите токен, а она вам операцию. Позволит вам отделить реализацию калькулятора, от набора операций

2022-12-25 10:22 UTC, alradish commented on Task_1_5_1/src/main/java/ru/nsu/fit/oop/lab6/Calculator.java
> +        Object[] wtf = Arrays.stream(str.split("\\s+")).map((s) -> {
wtf?

2022-12-25 10:22 UTC, alradish commented on Task_1_5_1/src/main/java/ru/nsu/fit/oop/lab6/Calculator.java
> +        operations.add(new Operation("-?\\d+(\\.\\d+)?", 0, (values, s) -> new Complex(Double.parseDouble(s))));
Вопрос: можно ли назвать числа операциями? Выглядит как костыль

2022-12-25 10:22 UTC, alradish commented on Task_1_5_1/src/test/java/ru/nsu/fit/oop/lab6/CalculatorTest.java
> +    static Stream<Arguments> getExpressions(){
Если хотите + за комплексные числа, добавьте тесты на них

2022-12-25 14:38 UTC, m1Myp commented
Словил шизу, но вроде сделал фактори, на доп бал не претендую, прошу проверить tree

2022-12-25 18:48 UTC, alradish requested changes

2022-12-25 18:48 UTC, alradish commented on Task_1_5_1/src/main/java/ru/nsu/fit/oop/lab6/OperationFactory.java
> +    public Token getOp(Operation op, String s) {
Фабрика принимает строку и выдаёт операцию. Т.е. всё знание об операциях надо перенести сюда

2022-12-26 05:44 UTC, alradish approved these changes

2022-12-26 05:45 UTC, merged